
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DialogData : Luban.BeanBase
{
    public DialogData(JSONNode _buf) 
    {
        { if(!_buf["DialogBoxType"].IsNumber) { throw new SerializationException(); }  DialogBoxType = (Enum.DialogType)_buf["DialogBoxType"].AsInt; }
        { if(!_buf["DialogContent"].IsString) { throw new SerializationException(); }  DialogContent = _buf["DialogContent"]; }
    }

    public static DialogData DeserializeDialogData(JSONNode _buf)
    {
        return new DialogData(_buf);
    }

    /// <summary>
    /// 对话框
    /// </summary>
    public readonly Enum.DialogType DialogBoxType;
    /// <summary>
    /// 台词
    /// </summary>
    public readonly string DialogContent;
   
    public const int __ID__ = 607934770;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DialogBoxType:" + DialogBoxType + ","
        + "DialogContent:" + DialogContent + ","
        + "}";
    }
}
}

