
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Table.TbCheeseDictionary TbCheeseDictionary {get; }
    public Table.TbCheeseScene TbCheeseScene {get; }
    public Table.TbDialog TbDialog {get; }
    public demo.Tbitem Tbitem {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCheeseDictionary = new Table.TbCheeseDictionary(loader("table_tbcheesedictionary"));
        TbCheeseScene = new Table.TbCheeseScene(loader("table_tbcheesescene"));
        TbDialog = new Table.TbDialog(loader("table_tbdialog"));
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCheeseDictionary.ResolveRef(this);
        TbCheeseScene.ResolveRef(this);
        TbDialog.ResolveRef(this);
        Tbitem.ResolveRef(this);
    }
}

}
