
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class WordContent : Luban.BeanBase
{
    public WordContent(JSONNode _buf) 
    {
        { if(!_buf["TypeOfWord"].IsNumber) { throw new SerializationException(); }  TypeOfWord = (Enum.CheeseWord)_buf["TypeOfWord"].AsInt; }
        { if(!_buf["WordChoice"].IsString) { throw new SerializationException(); }  WordChoice = _buf["WordChoice"]; }
    }

    public static WordContent DeserializeWordContent(JSONNode _buf)
    {
        return new WordContent(_buf);
    }

    /// <summary>
    /// 词性
    /// </summary>
    public readonly Enum.CheeseWord TypeOfWord;
    /// <summary>
    /// 单词
    /// </summary>
    public readonly string WordChoice;
   
    public const int __ID__ = -1141928465;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TypeOfWord:" + TypeOfWord + ","
        + "WordChoice:" + WordChoice + ","
        + "}";
    }
}
}

