
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class WordContent : Luban.BeanBase
{
    public WordContent(JSONNode _buf) 
    {
        { if(!_buf["TypeOfWord"].IsNumber) { throw new SerializationException(); }  TypeOfWord = (Enum.CheeseWordData)_buf["TypeOfWord"].AsInt; }
        { var __json0 = _buf["WordChoice"]; if(!__json0.IsArray) { throw new SerializationException(); } WordChoice = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  WordChoice.Add(__v0); }   }
    }

    public static WordContent DeserializeWordContent(JSONNode _buf)
    {
        return new WordContent(_buf);
    }

    /// <summary>
    /// 词性
    /// </summary>
    public readonly Enum.CheeseWordData TypeOfWord;
    /// <summary>
    /// 单词
    /// </summary>
    public readonly System.Collections.Generic.List<string> WordChoice;
   
    public const int __ID__ = -1141928465;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TypeOfWord:" + TypeOfWord + ","
        + "WordChoice:" + Luban.StringUtil.CollectionToString(WordChoice) + ","
        + "}";
    }
}
}

