
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Data
{
public sealed partial class CheeseDictionary : Luban.BeanBase
{
    public CheeseDictionary(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Icon"].IsString) { throw new SerializationException(); }  Icon = _buf["Icon"]; }
        { var __json0 = _buf["wordcontent"]; if(!__json0.IsArray) { throw new SerializationException(); } Wordcontent = new System.Collections.Generic.List<WordContent>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { WordContent __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.WordContent.DeserializeWordContent(__e0);  }  Wordcontent.Add(__v0); }   }
    }

    public static CheeseDictionary DeserializeCheeseDictionary(JSONNode _buf)
    {
        return new Data.CheeseDictionary(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    public readonly string Icon;
    public readonly System.Collections.Generic.List<WordContent> Wordcontent;
   
    public const int __ID__ = -856309103;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Wordcontent) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Icon:" + Icon + ","
        + "wordcontent:" + Luban.StringUtil.CollectionToString(Wordcontent) + ","
        + "}";
    }
}
}

