
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Data
{
public sealed partial class CheeseScene : Luban.BeanBase
{
    public CheeseScene(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["words"]; if(!__json0.IsArray) { throw new SerializationException(); } Words = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Words.Add(__v0); }   }
        { var __json0 = _buf["sentenceStructure"]; if(!__json0.IsArray) { throw new SerializationException(); } SentenceStructure = new System.Collections.Generic.List<Enum.CheeseWord>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Enum.CheeseWord __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (Enum.CheeseWord)__e0.AsInt; }  SentenceStructure.Add(__v0); }   }
    }

    public static CheeseScene DeserializeCheeseScene(JSONNode _buf)
    {
        return new Data.CheeseScene(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// int: cheeseDictionary id
    /// </summary>
    public readonly System.Collections.Generic.List<int> Words;
    public readonly System.Collections.Generic.List<Enum.CheeseWord> SentenceStructure;
   
    public const int __ID__ = 905983409;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "words:" + Luban.StringUtil.CollectionToString(Words) + ","
        + "sentenceStructure:" + Luban.StringUtil.CollectionToString(SentenceStructure) + ","
        + "}";
    }
}
}

