
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Data
{
public sealed partial class Dialog : Luban.BeanBase
{
    public Dialog(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["sceneId"].IsNumber) { throw new SerializationException(); }  SceneId = _buf["sceneId"]; }
        { var __json0 = _buf["dialogData"]; if(!__json0.IsArray) { throw new SerializationException(); } DialogData = new System.Collections.Generic.List<DialogData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { DialogData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.DialogData.DeserializeDialogData(__e0);  }  DialogData.Add(__v0); }   }
    }

    public static Dialog DeserializeDialog(JSONNode _buf)
    {
        return new Data.Dialog(_buf);
    }

    public readonly int Id;
    public readonly int SceneId;
    /// <summary>
    /// 0left1right
    /// </summary>
    public readonly System.Collections.Generic.List<DialogData> DialogData;
   
    public const int __ID__ = -1555745780;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in DialogData) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "sceneId:" + SceneId + ","
        + "dialogData:" + Luban.StringUtil.CollectionToString(DialogData) + ","
        + "}";
    }
}
}

