
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public partial class TbDialog
{
    private readonly System.Collections.Generic.Dictionary<int, Data.Dialog> _dataMap;
    private readonly System.Collections.Generic.List<Data.Dialog> _dataList;
    
    public TbDialog(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Data.Dialog>(count);
        _dataList = new System.Collections.Generic.List<Data.Dialog>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Data.Dialog _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Data.Dialog.DeserializeDialog(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Data.Dialog> DataMap => _dataMap;
    public System.Collections.Generic.List<Data.Dialog> DataList => _dataList;

    public Data.Dialog GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Data.Dialog Get(int key) => _dataMap[key];
    public Data.Dialog this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

