
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enum
{ 
    public enum CheeseWordData
    {
        /// <summary>
        /// 主语
        /// </summary>
        Subject = 1,
        /// <summary>
        /// usually verbs
        /// </summary>
        Predicate = 2,
        /// <summary>
        /// 宾语
        /// </summary>
        Object = 3,
        /// <summary>
        /// linking verbs
        /// </summary>
        Copula = 4,
        /// <summary>
        /// 表语
        /// </summary>
        Predicative = 5,
        Adjective = 6,
        Verb = 7,
    }

} 

